---
title: "Assignment 2 Task 2"
author: "Grace Kumaishi"
date: "1/31/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(lubridate)
library(stargazer)
library(janitor)
library(kableExtra)
library(ggbeeswarm)
```

```{r}
# Read in the data:
palmetto <- read_csv(here("data/palmetto.csv"), 
                     col_types = cols(.default = "c")) %>% # defaults all columns to character
  mutate(height = as.numeric(height)) %>% # mutate so that height is classified as numeric
  mutate(length = as.numeric(length)) %>% 
  mutate(width = as.numeric(width)) %>% 
  mutate(green_lvs = as.numeric(green_lvs)) %>% 
  mutate(species_name = case_when(
    species == 1 ~ "Serenoa repens",
    species == 2 ~ "Sabal etonia" 
  ))

# Make a subset of palmetto to simplify dataset
one_or_two <- palmetto %>% 
  select(species, height:green_lvs) %>% 
  mutate(species = as.factor(species))
```

### Exploratory data visualization:

```{r, fig.align = "center"}
ggplot(data = palmetto, aes(x = green_lvs, y = height, color = species_name)) +
  geom_point(alpha = .5) +
  scale_color_manual(values = c("seagreen3","coral1")) +
  labs(x = "Green leaves (count)",
       y = "Height (cm)",
       color = "Species name") +
  theme_minimal() 
```

**Figure 1:** 

```{r, fig.align = "center"}
ggplot() +
  geom_jitter(data = palmetto,
              aes(x = species_name, y = green_lvs, color = species_name),
              alpha = 0.2,
              width = 0.3) +
  scale_color_manual(values = c("seagreen3","coral1")) +
  geom_boxplot(data = palmetto, 
             aes(x = species_name, y = green_lvs),
             width = 0.5,
             size = 0.5,
             alpha = 0.5) +
  labs(x = "Species",
       y = "Green leaves (count)") +
  theme_minimal() +
  theme(legend.position = "none")
```

**Figure 2:**

```{r, fig.align = "center"}
ggplot(data = palmetto, aes(x = length, y = width, color = species_name)) +
  geom_point(alpha = .3) +
  facet_wrap(~species_name) +
  scale_color_manual(values = c("seagreen3","coral1")) +
  labs(x = "Length (cm)",
       y = "Width (cm)") +
  theme_minimal() +
  theme(legend.position = "none")
```

**Figure 3:**

### Binary logistic regression:

```{r,  echo = TRUE, warning = FALSE, message = FALSE}
# Create blr:
palmetto_blr <- glm(species ~ height + length + width + green_lvs, 
                            data = one_or_two, 
                            family = "binomial")

# Look at the model:
# palmetto_blr
# summary(palmetto_blr)

# Get a tidy version w/ broom: 
blr_tidy <- broom::tidy(palmetto_blr)

# Convert log odds to a probability:
blr_fitted <- palmetto_blr %>% 
  broom::augment(type.predict = "response")

# Quick viz with green leaves:
quick_viz <- ggplot(data = blr_fitted, aes(x = green_lvs, y = .fitted)) +
  geom_point(aes(color = species)) +
  geom_smooth(aes(color = species), se = FALSE) +
  labs(x = "Green leaves",
       y = "Probability of outcome 2")

# Effect plot for green leaves:
# effect_plot(palmetto_blr, 
            #pred = green_lvs, 
            #interval = TRUE, 
            #y.label = "Probability of '2'")
```

**Table 1:**

<div align="center">
```{r, results = "asis"}
stargazer(palmetto_blr, type = "html",
          title = "Binary Logistic Regression",
          dep.var.labels = "Species 2 (Sabal entonia)",
          covariate.labels = c("Height", "Length", "Width", "Green leaves"))
```
</div>

### Finalized table:

```{r}
blr_fitted_new <- blr_fitted %>% 
  select(species, .fitted) %>% 
  mutate(predicted_sp = case_when( # calculate predicted outcome with a cutoff at 50%
    .fitted >= .5 ~ "2", 
    .fitted < .5 ~ "1")) %>% 
  mutate(classification = case_when(
    species == predicted_sp ~ "Correct",
    species != predicted_sp ~ "Incorrect")) %>% 
  mutate(species = as.numeric(species)) %>% 
  group_by(species, classification) %>% 
  count(classification)

blr_fitted_table <- blr_fitted_new %>% 
  pivot_wider(names_from = classification,
              values_from = n) %>% 
  mutate(species = case_when(
    species == 1 ~ "Serenoa repens",
    species == 2 ~ "Sabal entonia")) %>% 
  column_to_rownames(var = "species") 

blr_fitted_table["Percent Correct"] = blr_fitted_table["Correct"] / (blr_fitted_table["Incorrect"] + blr_fitted_table["Correct"]) * 100 
```

**Table 2:**

```{r}
kable(blr_fitted_table, digits = 2) %>% 
  kable_styling(full_width = FALSE) %>% 
  column_spec(1, italic = TRUE) # Italicize first column only
```

### Citation:
[Abrahamson, W.G. 2019. Survival, growth and biomass estimates of two dominant palmetto species of south-central Florida from 1981 - 2017, ongoing at 5-year intervals ver 1. Environmental Data Initiative.](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.317.1)
